version: "3"
services:
  ganache:
    image: trufflesuite/ganache-cli
    environment:
      - MEW_RPC_URL=https://nodes.mewapi.io/rpc/eth
      - BLOCK_SCOUT_RPC_URL=https://mainnet-nethermind.blockscout.com/
      - MY_CRYPTO_RPC_URL=https://api.mycryptoapi.com/eth
      - CLOUDFLARE_RPC_URL=https://cloudflare-eth.com/
    entrypoint:
      - /bin/sh
      - -c
      - |
              node /app/ganache-core.docker.cli.js -f http://192.168.1.100:8544 -p 8545 -d
    ports:
      - "8545:8545"
    expose:
      - "8545"
    healthcheck:
      test: |
        curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":1}' http://localhost:8545
      interval: 30s
      timeout: 3s
      retries: 5

  ethtxd:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-ethtxd
    entrypoint:
      - /bin/sh
      - -c
      - |
          cd /ethtxd
          nix-shell shell-bin.nix --run '/usr/bin/ethtxd -p 3002 -r http://ganache:8545' --pure
    ports:
      - "3002:3002"
    expose:
      - "3002"
    healthcheck:
      test: curl localhost:3002
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - ganache

  miao-backend:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-miao-backend
    environment:
      - PORT=3001
      - ETHTXD_URL=http://ethtxd:3002
    entrypoint:
      - /bin/sh
      - -c
      - |
          cd /app
          yarn start
    ports:
      - "3001:3001"
    expose:
      - "3001"
    healthcheck:
      test: curl localhost:3001
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - ethtxd

  miao-frontend:
    build:
      context: .
      dockerfile: dockerfile/Dockerfile-miao-frontend
    environment:
      - BACKEND_URL=http://localhost:3001
    entrypoint:
      - /bin/sh
      - -c
      - |
          cd /app
          yarn serve
    ports:
      - "3000:3000"
    expose:
      - "3000"
    healthcheck:
      test: curl localhost:3000
      interval: 5s
      timeout: 3s
      retries: 5
    depends_on:
      - miao-backend
